-- =============================================
-- Main table: Reminders (recurring series)
-- =============================================
CREATE TABLE IF NOT EXISTS reminders (
    id                  TEXT PRIMARY KEY NOT NULL,   -- NanoID generated by the application

    title               TEXT NOT NULL,

    -- Recurrence data
    dtstart             DATETIME NOT NULL,           -- Start date/time (required)
    rrule               TEXT,                        -- RRULE string (e.g: FREQ=DAILY;INTERVAL=1). NULL = single event

    -- Recurrence limits (duplicated for easier queries)
    until               DATETIME,                    -- UNTIL=... (end date)
    count               INTEGER,                     -- COUNT=... (maximum number of occurrences)

    -- Critical field for the scheduler (performance)
    next_trigger        DATETIME NOT NULL,

    -- Metadata
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
    active              BOOLEAN DEFAULT 1 CHECK (active IN (0, 1))
);

CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_reminder_next_trigger
    ON reminders (next_trigger, active);
CREATE INDEX IF NOT EXISTS idx_reminder_dtstart
    ON reminders (dtstart);

-- =============================================
-- Exceptions table: individual instance editing
-- =============================================
CREATE TABLE IF NOT EXISTS exceptions (
    id                  TEXT PRIMARY KEY NOT NULL,   -- NanoID generated by the application

    reminder_id         TEXT NOT NULL,               -- Reference to reminders NanoID

    -- Which occurrence is being changed
    original_date       DATETIME NOT NULL,           -- Date that would be generated by the RRULE

    -- Exception type
    type                TEXT NOT NULL CHECK (type IN ('cancelled', 'modified')),

    -- Fields used only when type = 'modified'
    new_date            DATETIME,                    -- New date/time for this occurrence
    new_title           TEXT,                        -- New title (optional)

    -- Metadata
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (reminder_id) REFERENCES reminders(id) ON DELETE CASCADE
);

-- Unique index (prevents duplicating an exception on the same date)
CREATE UNIQUE INDEX IF NOT EXISTS idx_exception_unique
    ON exceptions (reminder_id, original_date);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_exception_reminder
    ON exceptions (reminder_id);